### ISSUE TITLE
Request for Waymo ReID Dataset

### ISSUE THREAD

**Issue by ldw200012** [bentherien/point-cloud-reid#1]
Hi, is Waymo ReID dataset also open for free access? I found your research interesting and want to test the evaluation on WaymoReID as well! (I succeed to test on the NuScenese ReID dataset following your instructions)

**Comment by bentherien** [comment]
Hi, I would be happy to help you get a version of Waymo ReID. I'm afraid it's slightly more complicated with Waymo due to the licensing restrictions placed on the dataset. Please send me an email about this at benjtherien at gmail dot com
