### ISSUE TITLE
about download the dataset

### ISSUE THREAD

**Issue by tinmale** [bentherien/point-cloud-reid#2]
I try to download the dataset, and before today, it just works even speed is a little slow, may be because i am located in east asia.
But today, the things changed, the download is suspended because of the connection problem, not just in my machine, also happened in my server, there are the informations below,

> nuscenes-reid-datas  44%[=======>            ] 268.41G  1002KB/s    in 33h 43m 
> 
> 2024-10-23 11:38:45 (2.26 MB/s) - Connection closed at byte 288201183850. Retrying.
> 
> --2024-10-23 11:38:46--  (try: 2)  https://wiselab.uwaterloo.ca/reid/compressed_datasets/nuscenes-reid-dataset.tar.gz
> Connecting to wiselab.uwaterloo.ca (wiselab.uwaterloo.ca)|129.97.26.232|:443... failed: Connection refused.
> Resolving wiselab.uwaterloo.ca (wiselab.uwaterloo.ca)... 129.97.26.232
> Connecting to wiselab.uwaterloo.ca (wiselab.uwaterloo.ca)|129.97.26.232|:443... failed: Connection refused.

![2024-10-23 19:40:28](https://github.com/user-attachments/assets/d937f223-a4b3-40b8-949c-1243374a3910)

I want to ask you if something happed in your server.

Thanks for your help!

**Comment by bentherien** [comment]
Hi @tinmale, we've recently been doing some work on the server, which may have caused the interruption.

Can try now? you can use `wget --continue https://wiselab.uwaterloo.ca/nuscenes-reid/compressed_datasets/nuscenes-reid-dataset.tar.gz` to resume the download

**Comment by tinmale** [comment]
hi @bentherien 
Thank you so much for kindly informing me about the issue. I've tried it, and the download now works perfectly on my server. I will close this comment. 
Wishing you all the best, and thanks again for your help!
